version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./app:/app
    command: npm run dev

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6379"